project:
  type: website
  output-dir: _site

website:
  site-url: "https://najlaabassi.github.io"
  page-footer: "© 2025 Najla Abassi | Built with Quarto"
  announcement:
    icon: info-circle
    dismissable: true
    content: "Pardon the dust! This website is currently being updated 🚧"
    type: danger
    position: above-navbar
  title: "Najla Abassi"
  navbar:
    page-layout: none
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Software"
        href: software.qmd
      - text: "Learning Logs"
        href: learning_logs.qmd
      - text: "Find Me Online"
        href: contact.qmd
format:
  html:
    theme:
      light: styles.scss
    css: styles.scss
