project:
  type: website
  output-dir: _site

website:
  site-url: "https://najlaabassi.github.io"
  page-footer: "© 2025 Najla Abassi | Built with Quarto"
  title: "Najla Abassi"
  navbar:
    page-layout: none
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Software"
        href: software.qmd
      - text: "TIL"
        href: today_i_learned.qmd
      - text: "Find Me Online"
        href: contact.qmd
  back-to-top-navigation: true
format:
  html:
    theme:
      light: styles.scss
    css: styles.scss
