---
title: "Portfolio"
format: html
---

## Research Experience

- **Research Associate, PhD student**, Department of Genomic Statistics and Bioinformatics, Institute of Medical Biostatistics, Epidemiology and Informatics (IMBEI), University Medical Center Mainz, Mainz, Germany (since 10.2023)
  - **SFB1292 Project**: Investigating the tissue repair program of Treg cells as an immune evasion strategy in tumor and chronic infections
    - **Thesis**: Developing an R/Bioconductor framework for structuring, managing, and exploring omics data analysis results (Supervisor: Dr. Federico Marini)
    
- **Reseach Assistant**, Laboratory of Biomedical Genomics and Oncogenetics, Institut Pasteur de Tunis, Tunis, Tunisia (04.2022-09.2023)
  - **Project**: Estimation of homozygosity in the Tunisian population from high throughput genotyping data
  
- **Research Assistant**, Laboratory of Anatomy and Pathological Cytology, Salah Azaiez Institute of Oncology, Tunis, Tunisia (06.2020-03.2021)
  - **Project**: Study of PD-L1 expression in anaplastic large cell lymphoma ALK (-)

## Scientific Community Activities

- **Package Reviewer**, Bioconductor (since May 2026)
- **Organizing Committee Member**, European Bioconductor Conference (EuroBioC) (since Sept 2024)
- **Mentor**, 16th Mainzer SommerUni Immunologie und Biomedizin (IRTG/SFB1292) (July 2024)

## Teaching

- [**iSEE Workshop**](https://github.com/iSEE/iUSEiSEE), IMBEI, University Medical Center Mainz, Germany (May 2024)
- [**Introduction to R**](https://github.com/imbeimainz/courseware_CTH_2024), IMBEI, University Medical Center Mainz, Germany (Feb 2024)
- [**Single cell data analysis Workshop**](https://github.com/imbeimainz/SingleCellRNAseqWorkshop2024), IMBEI, University Medical Center Mainz, Germany (Feb 2024)

## Codeathons

- **ASBCB Omics Codeathon April 2023**, African Society for Bioinformatics and Computational Biology
  - **Project**: Development of an open-source tool for the visualization of gene expression and variation data for biomarkers of neurological diseases
  - [GitHub Repo](https://github.com/omicscodeathon/neurovar)
  - [Publication](https://gigabytejournal.com/articles/143)

- **ASBCB Omics Codeathon Oct 2022**, African Society for Bioinformatics and Computational Biology
  - **Project**: Development of an R package for data analysis and visualization
  - [GitHub Repo](https://github.com/omicscodeathon/exvar)
  - [Publication](https://www.nature.com/articles/s41598-025-93067-5)
  
## Conference Presentations

### Invited Workshop

- **Streamlining Omics Data Visualization with iSEE and iSEEfier**
  - [Student Conference on Biological Sciences 2024 (SCBS2024)](https://sites.google.com/fshn.edu.al/scbs-2024/home)
  - [Material](https://github.com/NajlaAbassi/iSEEfierWorkshopSCBS2024)
  
### Short Talk

  - [EuroBioC2024](https://eurobioc2024.bioconductor.org/)
  - **Slides** : [One class to rule them all: DeeDeeExperiment for managing and exploring omics analysis results](https://doi.org/10.5281/zenodo.17184376)

### Poster


- [EuroBioC2026](https://eurobioc2026.bioconductor.org/)
  - [EMMA: Enrichment Methods Matter for achieving fully Reproducible Pathway Analysis](https://doi.org/10.5281/zenodo.20446276)

- [EuroBioC2025](https://eurobioc2025.bioconductor.org/)
  - iSEEfier: Starting to use iSEE became even easier





