---
title: "Publications"
format: html
---

[Google scholar](https://scholar.google.com/citations?user=XY4UafAAAAAJ&hl=en)

## Research Papers

### 2026

* Lossa, J., Schnöder, T. M., Ronge, Z., Haasch, N., Hodapp, K., Marini, F., **Abassi, N.**, … Muth, S. (2026). Type I interferon-activated NK cells control polycythemia vera in vivo. **Blood**, (blood.2026033951). ([doi](doi:10.1182/blood.2026033951))

* **Abassi, N.**, Schwarz, L., Filippi, E., & Marini, F. (2026). DeeDeeExperiment: Building an infrastructure for integrating and managing omics data analysis results in R/Bioconductor. **Bioinformatics**. ([doi](https://doi.org/10.1093/bioinformatics/btag157))

### 2025

* Nedwed, A. S., Ustjanzew, A., **Abassi, N.**, Dammer, L., Schulze, A., Helbich, S. S., Delacher, M., Strauch, K., & Marini, F. (2025). GeDi: simplifying gene set distances for enhanced omics interpretation in R/Bioconductor. **BMC Bioinformatics**, 27(1), 14. ([doi](https://doi.org/10.1186/s12859-025-06335-6))

* Hemberg, M., Marini, F., Ghazanfar, S., Ajami, A. A., **Abassi, N.**, Anchang, B., Benayoun, B. A., Cao, Y., Chen, K., Cuesta-Astroz, Y., DeBruine, Z., Dendrou, C. A., De Vlaminck, I., Imkeller, K., Korsunsky, I., Lederer, A. R., Li, J. J., Meysman, P., Miller, C. L., . . . Jelic, I. (2025). Insights, opportunities, and challenges provided by large cell atlases. **Genome Biology**, 26(1), 358. ([doi](https://doi.org/10.1186/s13059-025-03771-8))

* Aribi, H. B., Dixon, I., **Abassi, N.**, & Awe, O. I. (2025). Efficient and easy gene expression and genetic variation data analysis and visualization using exvar. **Scientific Reports**, 15(1). ([doi](https://doi.org/10.1038/s41598-025-93067-5))

* Weinmann-Menke, J., Gonzalez-Sanchez, H. M., Iwata, Y., Meineck, M., **Abassi, N.**, Marini, F., Granados-Contreras, F., Takakura, A., Noda, M., & Kelley, V. R. (2025). PTPRZ signaling, Tubule- and Macrophage-Mediated Kidney Injury, and subsequent CKD. **Journal of the American Society of Nephrology**. ([doi](https://doi.org/10.1681/ASN.0000000640))

### 2024

* Aribi, H. B., **Abassi, N.**, & Awe, O. I. (2024). NeuroVar: an open-source tool for the visualization of gene expression and variation data for biomarkers of neurological diseases. **Gigabyte**, 2024. ([doi](https://doi.org/10.46471/gigabyte.143))

* Mezzi, N., **Abassi, N.**, Fatnassi, F., Abdelhak, S., & Romdhane, L. (2024). Consanguinité et son impact sur la santé et la dynamique du génome : Un exemple de la Tunisie. **La Tunisie Médicale**, 102(5). ([doi](https://doi.org/10.62438/tunismed.v102i5.4787))

* Romdhane, L., Kefi, S., Mezzi, N., **Abassi, N.**, Jmel, H., Romdhane, S., Shan, J., Chouchane, L., & Abdelhak, S. (2024). Ethnic and functional differentiation of copy number polymorphisms in Tunisian and HapMap population unveils insights on genome organizational plasticity. **Scientific Reports**, 14(1). ([doi](https://doi.org/10.1038/s41598-024-54749-8))


## Preprints & Abstracts

### 2026

* Rausch, J., Wendel, P., Dzama-Karels, M., Steiner, M., Gierschek, F., Fetsch, V., Knapp, L. R., **Abassi, N.**, Kuhmann, M., Viehböck, L., Weisemann, S., Dolgikh, N., Habermann, J., Lahrmann, C., Klein, M., Delacher, M., Wölfel, C., Döhner, K., Döhner, H., . . . Kühn, M. W. (2026). Menin-Inhibition sensitizes acute myeloid leukemia to CLEC12A-Directed CAR cell therapy. bioRxiv (Cold Spring Harbor Laboratory). ([doi](https://doi.org/10.64898/2026.02.15.703376))

### 2025

* Damara, A., **Abassi, N.**, Mihoc, D., Nastaranpour, M., Kraft, P., Sarkar, T., Deppermann, C., Mayer, J. U., Grabbe, S., Delacher, M., Marini, F., & Shahneh, F. (2025). KDM6B inhibition modulates monocyte activation and alleviates IMQ-psoriasis skin inflammation. bioRxiv (Cold Spring Harbor Laboratory). ([doi](https://doi.org/10.1101/2025.10.13.682023))

### 2024

* Legscha, K. J. J., Märker, L. P., **Abassi, N.**, Yilmaz, A., Woelfel, C., Ferreira, E. A., Nedwed, A., Helbich, S. S., Delacher, M., Marini, F., Porubsky, S., Theobald, M., & Echchannaoui, H. (2024b). Deep cellular and molecular characterization reveal a distinct phenotype and metabolic signature of human senescent CD8+ T cells: Implication for cancer cellular therapy. Blood, 144(Supplement 1), 2536. ([doi](https://doi.org/10.1182/blood-2024-194719))



